# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000004)
$foreground = rgb(DDC4C8)
$color0 = rgb(000004)
$color1 = rgb(212730)
$color2 = rgb(222730)
$color3 = rgb(232730)
$color4 = rgb(633B42)
$color5 = rgb(5E4749)
$color6 = rgb(774249)
$color7 = rgb(C6A3A7)
$color8 = rgb(8B7275)
$color9 = rgb(2C3440)
$color10 = rgb(2E3440)
$color11 = rgb(2F3440)
$color12 = rgb(844F59)
$color13 = rgb(7E5E62)
$color14 = rgb(9F5761)
$color15 = rgb(C6A3A7)
