# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(17161B)
$foreground = rgb(F9EAEB)
$color0 = rgb(3E3D43)
$color1 = rgb(49435A)
$color2 = rgb(4B425A)
$color3 = rgb(756275)
$color4 = rgb(84707A)
$color5 = rgb(948697)
$color6 = rgb(B39295)
$color7 = rgb(EED8DA)
$color8 = rgb(A79799)
$color9 = rgb(615A78)
$color10 = rgb(645979)
$color11 = rgb(9C839C)
$color12 = rgb(B095A3)
$color13 = rgb(C5B3C9)
$color14 = rgb(EFC2C6)
$color15 = rgb(EED8DA)
