# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E9D7E9
background         #121111
cursor             #7E747B

active_tab_foreground     #121111
active_tab_background     #E9D7E9
inactive_tab_foreground   #E9D7E9
inactive_tab_background   #121111

active_border_color   #E9D7E9
inactive_border_color #121111
bell_border_color     #0F0D0B

color0      #3A3939
color1		#0F0D0B
color2		#0F0D0B
color3		#472C43
color4		#492E44
color5		#906A8F
color6		#906A8F
color7		#D7BDD6
color8		#968596
color9		#14110E
color10		#14110E
color11		#5E3B59
color12		#613D5B
color13		#C08DBF
color14		#C08DBF
color15		#D7BDD6
