# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# as per Hyprland wiki: hyprland-qt-support provides a QML style for hypr* qt6 apps                                                         

roundess = 6

border_width = 0

reduce_motion = false
