Net/ThemeName "Kali-Dark"
Net/IconThemeName "candy-icons"
Gtk/CursorThemeName "Bibata-Modern-Ice"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/RGBA "rgb"
